CREATE DATABASE IF NOT EXISTS COLLEGE;
USE COLLEGE;

CREATE TABLE TEACHER(
ID INT UNIQUE,
NAME VARCHAR(20) NOT NULL,
SUBJECT VARCHAR(10),
SALARY bigint
);

INSERT INTO TEACHER
(ID,NAME,SUBJECT,SALARY)
VALUES
(23,"AJAY","MATH",50000),
(47,"BHARAT","ENGLISH",60000),
(18,"CHETAN","CHEMISTRY",45000),
(9,"DIVYA","PHYSICS",75000);

SELECT * FROM TEACHER;

ALTER TABLE TEACHER 
MODIFY ID INT PRIMARY KEY;

SELECT * 
FROM TEACHER 
WHERE SALARY>55000;

ALTER TABLE TEACHER
CHANGE COLUMN SALARY CTC BIGINT;

UPDATE TEACHER
SET CTC=75000
WHERE NAME="DIVYA";

UPDATE TEACHER 
SET CTC=CTC+CTC*0.25;

SET SQL_SAFE_UPDATES=0;

ALTER TABLE TEACHER
ADD COLUMN CITY VARCHAR(10)default "GURGAO";

ALTER TABLE TEACHER
DROP COLUMN CTC ;
